version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: notetaking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: notetaking_db
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
